@host = http://localhost:8080/api/v1
@access_token = <JWT_ACCESS_TOKEN>
@refresh_token = <JWT_REFRESH_TOKEN>

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
} 

###
POST {{host}}/auth/refresh
Content-Type: application/json
X-Refresh-Token: {{refresh_token}}
Authorization: Bearer {{access_token}}
